version: '3.8'
services:
  nginx:
    image: nginx:alpine
    build:
      context: docker/nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - 443:443
